name = "PlutoTool"
uuid = "fd22e955-59d9-4d33-af65-18589d3615af"
authors = ["MarkNahabedian <naha@mit.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
